#define ONE_SECOND          1000
#define SECONDS_IN_MINUTE   60
#define MINUTES_IN_HOUR     60
#define HOURS_IN_DAY        24
#define DAYS_IN_WEEK        7
const long ONE_MINUTE = long(ONE_SECOND) * SECONDS_IN_MINUTE;
const long ONE_DAY = ONE_MINUTE * MINUTES_IN_HOUR * HOURS_IN_DAY;
const int SERIAL_MONITOR_STARTUP_DELAY = ONE_SECOND * 3;
const int BUILTIN_LED_ON_TIME = 10;
const long JOIN_TIMEOUT = ONE_MINUTE * 4;
const int DELAY_WHILE_PRESSING_TIME_CHANGE_BUTTON = 150;
