#define ONE_SECOND          1000
#define SECONDS_IN_MINUTE   60
const int ONE_MINUTE = ONE_SECOND * SECONDS_IN_MINUTE;
const int SERIAL_MONITOR_STARTUP_DELAY = ONE_SECOND * 3;
const int BUILTIN_LED_ON_TIME = 10;
